config/routes.rb
Rails.application.routes.draw do
  get 'start/index'
  resources :posts


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'start#index'

  get '/home', to: 'home#show'
  get '/about', to: 'about#show'
  get '/contact', to: 'contact#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def show
      render 'about/about'
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def show
      render 'contact/contact'
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
      render 'home/home'
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/views/about/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: black;
            color: white;
        }
        .navbar {
            border: 1px solid white}
        .navbar-nav {
            color: white
        }
        .nav-link {
        color: white
        }       
        .vertical-space {
            height: 540px;
        }
    </style>
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img src="/Y.png"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                    <%= link_to 'Home', home_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                <%= link_to 'About', about_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Contact', contact_path, class: 'nav-link' %>
                </li>
                </ul>
            </div>
        </div>
    </nav>

<div class="titulo">
    <h1>    About page</h1>
    <h2>    Subtitle text for the second page</h2>
    <p> a litle parragraph about the page about </p>
</div>

<div class="vertical-space"></div>

<footer class="footer">
        <div class="container">
            <p>Copyright &copy; <%= Time.now.year %> Landing Page</p>
            <div class="social-media">
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-facebook"></i></a>
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-twitter"></i></a>
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-instagram"></i></a>
            </div>
        </div>
    </footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

</body>
</html>

app/views/contact/contact.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: black;
            color: white;
        }
        .navbar {
            border: 1px solid white}
        .navbar-nav {
            color: white
        }
        .nav-link {
        color: white
        }       
        .vertical-space {
            height: 240px;
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img src="/Y.png"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to 'Home', home_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'About', about_path, class:'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Contact', contact_path, class: 'nav-link' %>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <h1>Contact page</h1>
        
        <br>
        <form>
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email">
            </div>
            <div class="mb-3">
                <label for="message" class="form-label">Message</label>
                <textarea class="form-control" id="message" name="message" rows="5"></textarea>
            </div>
                <button type="submit" class="btn btn-primary" id="submit-button">Submit</button>
            
            </form>


        
        <div id="thanks" style="display: none; color: white;">
            Thank you for your message, we will contact you soon...
        </div>

        <script> 
        const submitButton = document.getElementById("submit-button");
        const thanksMessage = document.getElementById("thanks");
        

        submitButton.addEventListener("click", function() {
            thanksMessage.style.display = "block";
        });
        </script>





    </div>
    <div class="vertical-space"></div>
    <p>when the page is refreshed the message of "thanks" disappears</p>

    <footer class="footer">
        <div class="container">
            <p>Copyright &copy; <%= Time.now.year %> Landing Page</p>
            <div class="social-media">
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-facebook"></i></a>
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-twitter"></i></a>
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-instagram"></i></a>
            </div>
        </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
</body>
</html>

app/views/home/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: black;
            color: white;
        }
        .navbar {
            border: 1px solid white}
        .navbar-nav {
            color: white
        }
        .nav-link {
        color: white
        }       
        .vertical-space {
            height: 540px;
        }
    </style>
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img src="/Y.png"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                    <%= link_to 'Home', home_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                <%= link_to 'About', about_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Contact', contact_path, class: 'nav-link' %>
                </li>
                </ul>
            </div>
        </div>
    </nav>

<div class="titulo">
    <h1>    Home page</h1>
    <h2>    Subtitle text for the page</h2>
</div>

<div class="vertical-space"></div>

<footer class="footer">
        <div class="container">
            <p>Copyright &copy; <%= Time.now.year %> Landing Page </p>
            <div class="social-media">
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-facebook"></i></a>
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-twitter"></i></a>
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-instagram"></i></a>
            </div>
        </div>
    </footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Y</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/start/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: black;
            color: white;
        }
        .navbar {
            border: 1px solid white}
        .navbar-nav {
            color: white
        }
        .nav-link {
        color: white
        }       
        .vertical-space {
            height: 540px;
        }
    </style>
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img src="/Y.png"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <%= link_to 'Home', home_path, class: 'nav-link' %>
                    </li>
                    <li class="nav-item">
                    <%= link_to 'About', about_path, class:'nav-link' %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Contact', contact_path, class: 'nav-link' %>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

<div class="titulo">
    <h1>    First page in ruby</h1>
    <h2>    Subtitle line text</h2>
    <p> Text of the page</p><br>
</div>

<div class="vertical-space"></div>

<footer class="footer">
        <div class="container">
            <p>Copyright &copy; <%= Time.now.year %> Landing Page </p>
            <div class="social-media">
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-facebook"></i></a>
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-twitter"></i></a>
                <a href="#" class="btn btn-outline-light btn-social mx-1"><i class="bi bi-instagram"></i></a>
            </div>
        </div>
    </footer>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

</body>
</html>